variable "instance_type" {}
variable "project_name" {}
variable "ecs_security_group" {}
variable "asg_max_size" {}
variable "asg_min_size" {}
variable "private_subnet_a_id" {}
variable "private_subnet_b_id" {}
variable "target_group_arn" {}
variable "vpc_id" {}