name: Deploy lambda on change

on:
    push:
        branches:
            - main
        paths:
            - modules/order/lambda/python/get-cart.py

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Package code
              working-directory: ./modules/order/lambda/python
              run: zip -j get-cart.zip get-cart.py

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-west-1
            
            - name: Upload to S3
              run: |
                aws s3 cp get-cart.zip s3://lambda-cart-service/get-cart.zip

            - name: Update lambda function
              run: |
                aws lambda update-function-code \
                  --function-name get-cart \
                  --s3-bucket lambda-cart-service
                  --s3-key get-cart.zip
                    